platform :ios,'7.0'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
pod 'AFNetworking'
pod 'Masonry', '~> 0.6.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~> 3.7.2'
pod 'LKDBHelper', '~> 2.1.3'
pod 'MJExtension'
pod 'ReactiveCocoa'
pod 'SVPullToRefresh'
pod 'TMCache'
pod 'CocoaAsyncSocket'
pod 'CocoaLumberjack'
pod 'AFDownloadRequestOperation'
pod 'MagicalRecord'
pod 'CocoaHTTPServer'
pod 'iCarousel'
pod 'GPUImage'
pod 'BlocksKit'
pod 'Nimbus'
pod 'FLEX'
pod 'SWTableViewCell'
pod 'TTTAttributedLabel'
pod 'TSMessages'
pod 'WebViewJavascriptBridge'
pod 'AMScrollingNavbar'
pod 'TPKeyboardAvoiding'
pod 'DBCamera', '~> 2.4'
pod 'Mantle'
pod 'Toast'
pod 'RDVTabBarController'
pod 'kingpin'
